platform :ios, '8.0'
use_frameworks!

pod 'Parse'
pod 'Bond'
pod 'SVProgressHUD'
pod 'JSQMessagesViewController'
pod 'EBCardCollectionViewLayout'
pod 'Firebase', '~> 2.5'
pod 'DateTools'
pod "Popover"
